/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Companhia_AereaDAO;
import dao.VooDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Companhia_Aerea;
import model.Voo;

/**
 *
 * @author Felipe TI
 */
public class Filtrar_Voo extends javax.swing.JFrame {

    /**
     * Creates new form Filtrar_Voo
     */
    public Filtrar_Voo() {
        initComponents();
        CarregarCompanhias();
             

    }
    
    private void CarregarCompanhias(){
            
        List<Companhia_Aerea> listaCompanhia = 
                Companhia_AereaDAO.getCompanhias();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        Companhia_Aerea fake = new Companhia_Aerea();
        fake.setId(0);
        fake.setNome_Fantasia("Selecione...");
        model.addElement( fake.getNome_Fantasia() );
        for (Companhia_Aerea comp : listaCompanhia) {
            model.addElement( comp.getNome_Fantasia() );
        }
        CbBoxCompanhia.setModel( model );
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAeroportoEmbarque = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAeroportoDesembarque = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CbBoxCompanhia = new javax.swing.JComboBox<>();
        FtxtData = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Aeroporto de Embarque");

        txtAeroportoEmbarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAeroportoEmbarqueActionPerformed(evt);
            }
        });

        jLabel2.setText("Aeroporto de Desembarque");

        jLabel3.setText("Companhia Aerea");

        CbBoxCompanhia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Gol", "Azul", "Latam", "Aerolineas Argentinas" }));
        CbBoxCompanhia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbBoxCompanhiaActionPerformed(evt);
            }
        });

        try {
            FtxtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FtxtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FtxtDataActionPerformed(evt);
            }
        });

        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Data do Voo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CbBoxCompanhia, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(FtxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAeroportoEmbarque, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAeroportoDesembarque, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAeroportoEmbarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAeroportoDesembarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CbBoxCompanhia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FtxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FtxtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FtxtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FtxtDataActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       
        if( !"".equals(txtAeroportoEmbarque.getText())) {
            
            Voo_Filtrado tela = new Voo_Filtrado();
            tela.limpar();
            List<Voo> consulta = VooDAO.getVoosAeroporto(txtAeroportoEmbarque.getText(),'p');
            if(consulta != null){
            tela.filtrar(consulta);
            tela.setVisible(true);
            this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Não foram encontrado voos para esse aeroporto!");
            }
            
        }else if( !"".equals(txtAeroportoDesembarque.getText())) {
            Voo_Filtrado tela = new Voo_Filtrado();
            tela.limpar();
            List<Voo> consulta = VooDAO.getVoosAeroporto(txtAeroportoDesembarque.getText(),'d');
            if(consulta != null){
            tela.filtrar(consulta);
            tela.setVisible(true);
            this.dispose();
            }
        }else if(!"Selecione...".equals(CbBoxCompanhia.getSelectedItem())) {
            Voo_Filtrado tela = new Voo_Filtrado();
            tela.limpar();
            tela.setVisible(true);
            this.dispose();
        }else if ( !"  /  /    ".equals(FtxtData.getText())){
            Voo_Filtrado tela = new Voo_Filtrado();
            tela.limpar();
            tela.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Não há filtro digitado!");
        }      
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void txtAeroportoEmbarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAeroportoEmbarqueActionPerformed

    }//GEN-LAST:event_txtAeroportoEmbarqueActionPerformed

    private void CbBoxCompanhiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbBoxCompanhiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbBoxCompanhiaActionPerformed
   /*
    
    teste
    
    */
    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbBoxCompanhia;
    private javax.swing.JFormattedTextField FtxtData;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAeroportoDesembarque;
    private javax.swing.JTextField txtAeroportoEmbarque;
    // End of variables declaration//GEN-END:variables
}
